baseURL      = "https://qisrepo.top/"
languageCode = "zh-CN"
title        = "QisRepo"
theme        = "hextra"

defaultContentLanguage = "zh-CN"

enableRobotsTXT = true
# Parse Git commit
enableGitInfo  = true
enableEmoji    = true
hasCJKLanguage = true

enableInlineShortcodes = true

[outputs]
  home    = ["html"]
  page    = ["html"]
  section = ["html", "rss"]

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight       = 1
  [languages.id]
    languageName = "Indonesian"
    languageCode = "id"
    weight       = 2
  [languages.zh-cn]
    languageName = "简体中文"
    languageCode = "zh-CN"
    weight       = 3

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    pageRef    = "/notes"
    weight     = 1
  [[menu.main]]
    name   = "Search"
    weight = 10
    [menu.main.params]
      type = "search"
  
  [[menu.sidebar]]
    identifier = "more"
    name = "More"
    weight = 1
    [[menu.sidebar.params]]
      type = "separator"
  [[menu.sidebar]]
    name = "Tags"
    url = "/tags/"
    weight = 2



[params]
  description = "Qi's repository, which is used to store personal results"
  dateFormat  = "2006-01-02"
  displayUpdatedDate = true
  [params.navbar]
    [params.navbar.logo]
      path = "favicon.svg"
      dark = "favicon.svg"
  [params.footer]
    displayCopyright = true
  [params.editURL]
    enable = false
  [params.blog]
    [params.blog.list]
      displayTags = true
    [params.blog.article]
      displayPagination = true
